### ISSUE TITLE
拖尾轨迹放大后有白线

### ISSUE THREAD

**Issue by muzi131313** [SilentTiger/laser-pen#1]
![image](https://user-images.githubusercontent.com/2398149/149094589-235986f4-5a89-4b57-8ff0-c99ea3251084.png)
rgba颜色设置：`rgba(135, 90, 120, 1) `
delay: 0.4s
maxWidth: 20px
tension: 0.1
opacity: 1

**Comment by SilentTiger** [comment]
我猜测是因为 canvas 绘制贝塞尔曲线的时候有一点点误差。因为绘制的逻辑是绘制很多条贝塞尔曲线拼接成最终的鼠标轨迹，所以这个空隙可能是曲线 n 的结束和曲线 n + 1 的开始之间的这个位置产生的。
不过我暂时没想到什么特别好的办法，你要是有什么 idea 可以讨论一下。

**Comment by SilentTiger** [comment]
通过将每一段曲线的开始和结束点分别向前和向后移动一点点距离(在这个点所在的方向上移动 0.005px)，使得 canvas 的绘制误差尽可能的不容易被察觉。0.005px 这个值是我反复实验后得出的一个经验值，也不能移动太多，过多会使得半透明的线条有明显的重叠部分，看起来也很奇怪。
